cmake_minimum_required(VERSION 3.17)
project(acme_windowing_haiku CXX)
add_library(${PROJECT_NAME} SHARED haiku_windowing.cpp _factory.cpp native.cpp)
add_library(static_${PROJECT_NAME} STATIC haiku_windowing.cpp _factory.cpp native.cpp)
foreach(target ${PROJECT_NAME} static_${PROJECT_NAME})
 target_compile_features(${target} PRIVATE cxx_std_20)
 target_compile_options(${target} PRIVATE -fpermissive)
 target_include_directories(${target} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/..)
endforeach()
target_compile_definitions(static_${PROJECT_NAME} PRIVATE CUBE)
target_link_libraries(${PROJECT_NAME} PRIVATE acme be)
target_link_options(${PROJECT_NAME} PRIVATE -Wl,-z,defs)
target_link_libraries(static_${PROJECT_NAME} PRIVATE static_acme be)
