cmake_minimum_required(VERSION 3.17)
project(windowing_haiku CXX)
add_library(${PROJECT_NAME} SHARED window.cpp windowing.cpp display.cpp monitor.cpp graphics.cpp text_composition_client.cpp shell.cpp native_file_icon.cpp icon.cpp _factory.cpp)
add_library(static_${PROJECT_NAME} STATIC window.cpp windowing.cpp display.cpp monitor.cpp graphics.cpp text_composition_client.cpp shell.cpp native_file_icon.cpp icon.cpp _factory.cpp)
foreach(target ${PROJECT_NAME} static_${PROJECT_NAME})
 target_compile_features(${target} PRIVATE cxx_std_20)
 target_compile_options(${target} PRIVATE -fpermissive)
 target_include_directories(${target} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/..)
endforeach()
target_compile_definitions(static_${PROJECT_NAME} PRIVATE CUBE)
target_link_libraries(${PROJECT_NAME} PRIVATE acme apex aqua aura acme_windowing_haiku innate_ui_haiku be)
target_link_options(${PROJECT_NAME} PRIVATE -Wl,-z,defs)
target_link_libraries(static_${PROJECT_NAME} PRIVATE static_acme static_apex static_aqua static_aura static_acme_windowing_haiku innate_ui_haiku be)
